const fs=require("fs");
const J=f=>{const t=fs.readFileSync(f,"utf8");const s=t.indexOf("{");let d=0,e=s,q=false,esc=false;for(;e<t.length;e++){const c=t[e];if(q){if(esc)esc=false;else if(c=="\\")esc=true;else if(c=='"')q=false;continue}if(c=='"')q=true;else if(c=="{")d++;else if(c=="}"){d--;if(!d)break}}return JSON.parse(t.slice(s,e+1))};
const band=f=>{const t=fs.readFileSync(f,"utf8");const m=t.match(/BAND \S+: Befehle (\d+)\/\d+ .*?Dreiecke (\d+)k\/\d+k .*?VRAM MB ([\d.]+)\/\d+ .*?GPU ms\/Frame ([\d.]+)/);const tier=t.match(/^tier\*\s+(\d+)\/\d+/m);const baum=t.match(/^baum\s+(\d+)\/\d+\s+(\S+)\s+(\S+)\//m);return {cmd:+m[1],tri:+m[2],vram:+m[3],bg:+m[4],tier:tier?+tier[1]:0,baum:baum?baum[1]+" "+baum[2]+" "+baum[3]:"-",pool:(t.match(/STEMPEL-POOL (\S+)/)||[])[1]||"-"}};
const rows=[];
for(let i=1;i<=8;i++){const N=i+(i%2?"A":"B");const r={N,X:N.slice(-1)};
 for(const R of ["voll","frei"]){const l=J(`${N}-lauf-${R}.json`);const dr=l.draws?l.draws.p50:l.befehle.mittel;const tr=l.dreiecke.p50!=null?l.dreiecke.p50:l.dreiecke.mittel;
  r[R]={fps:l.fps,p50:l.frameMs.p50,p95:l.frameMs.p95,max:l.frameMs.max,c50:l.cpuTaktMs.p50,c95:l.cpuTaktMs.p95,ren:l.phasenEwmaMs.render,cre:l.phasenEwmaMs.creatures,str:l.phasenEwmaMs.streaming,dur:l.gpuDurchsatzMs&&l.gpuDurchsatzMs.p50,draws:dr,tri:Math.round(tr/1e3),gueltig:l.stempel&&l.stempel.gueltig,wetter:l.wetter,wache:l.wetterHalt&&l.wetterHalt.urteil,ue33:l.ueber33}}
 for(const y of ["yaw0","yaw088"]){const g=J(`${N}-gpubank-${y}.json`);r["bank_"+y]=g.gpuJeFrameMs;r["bcpu_"+y]=g.cpuJeFrameMs;r["band_"+y]=band(`${N}-band-${y}.txt`)}
 const z=J(`${N}-zaehlen.json`);r.tiere=(z.klassen||[]).filter(k=>/tier/.test(k.klasse)).map(k=>k.klasse.replace("tier:","")+" "+k.cmd).join(",")||"-";
 const p=J(`${N}-profil.json`);r.profil={fps:p.fps,selbst:p.selbst.slice(0,10),gesamt:p.gesamt};
 r.ende=J(`${N}-ende.json`).ergebnis;rows.push(r);
 const v=r.voll,f=r.frei,b0=r.band_yaw0,b8=r.band_yaw088;
 console.log(`${N} voll ${v.fps}fps ${v.p50}/${v.p95} max ${v.max} cpu ${v.c50}/${v.c95} ren ${v.ren} cre ${v.cre} dur ${v.dur} ${v.wetter}${v.wache?"("+v.wache+")":""} | frei ${f.fps}fps ${f.p50}/${f.p95} max ${f.max} cpu ${f.c50}/${f.c95} ren ${f.ren} cre ${f.cre} ${f.wetter}${f.wache?"("+f.wache+")":""} | bank ${r.bank_yaw0}/${r.bcpu_yaw0} · ${r.bank_yaw088}/${r.bcpu_yaw088} | band0 ${b0.cmd}/${b0.tri}k/${b0.vram}/${b0.bg} baum[${b0.baum}] band88 ${b8.cmd}/${b8.tri}k/${b8.vram}/${b8.bg} baum[${b8.baum}] ${b0.pool} | tiere ${r.tiere} | ende ${r.ende.wetter} | profil-fps ${p.fps}`);}
fs.writeFileSync("zusammen.json",JSON.stringify(rows,null,1));
const med=a=>{a=a.filter(x=>x!=null).sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2};
const G=(X,fn,ohne)=>rows.filter(r=>r.X===X&&(!ohne||r.N!==ohne)).map(fn);
const K={"voll p50":r=>r.voll.p50,"voll p95":r=>r.voll.p95,"voll fps":r=>r.voll.fps,"voll cpu50":r=>r.voll.c50,"voll cpu95":r=>r.voll.c95,"voll render":r=>r.voll.ren,"voll creat":r=>r.voll.cre,"voll durchs":r=>r.voll.dur,"voll >33%":r=>r.voll.ue33,"frei p50":r=>r.frei.p50,"frei p95":r=>r.frei.p95,"frei fps":r=>r.frei.fps,"frei cpu50":r=>r.frei.c50,"frei cpu95":r=>r.frei.c95,"frei render":r=>r.frei.ren,"frei creat":r=>r.frei.cre,"bank yaw0":r=>r.bank_yaw0,"bank -0.88":r=>r.bank_yaw088,"bankcpu yaw0":r=>r.bcpu_yaw0,"band cmd yaw0":r=>r.band_yaw0.cmd,"band tri yaw0":r=>r.band_yaw0.tri,"band vram yaw0":r=>r.band_yaw0.vram,"band gpu yaw0":r=>r.band_yaw0.bg,"band cmd -0.88":r=>r.band_yaw088.cmd,"band tri -0.88":r=>r.band_yaw088.tri,"band vram -0.88":r=>r.band_yaw088.vram,"band gpu -0.88":r=>r.band_yaw088.bg,"band tier yaw0":r=>r.band_yaw0.tier};
console.log("\nMEDIAN  A | B | B-A | B ohne 2B   (A ; B)");for(const [k,fn] of Object.entries(K)){const a=G("A",fn),b=G("B",fn),b2=G("B",fn,"2B");console.log(k.padEnd(15),med(a).toFixed(2).padStart(8),med(b).toFixed(2).padStart(8),(med(b)-med(a)).toFixed(2).padStart(8),med(b2).toFixed(2).padStart(8),"  ",a.join(" "),";",b.join(" "))}
